name: Main

on:
  push:
    branches: ['feature/multi-arch']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'
      - uses: docker/setup-buildx-action@v2
      - name: Build
        run: ./build.sh
